### PR TITLE
avoid double compression while loading images

### PR DESCRIPTION
**Pull request by gentoomaniac**
@Shulyaka
The Idea is to create a thumbnail if none exists and caching is enabled.
Afterwards we try sending with readfile.
In case that fails or caching is disabled we encode on the fly via create_thumb and cached filename "null"

### CODE REVIEW

**Comment by Shulyaka** [comment]
This way we are doubling the execution time if caching is enabled but failed. My approach is to have a single function that outputs thumbnail and writes to cache (if needed and able) simultaneously without any double work and without the need to write-then-read-again: https://github.com/Shulyaka/minigal-nano-ng/blob/master/src/createthumb.php

**Comment by gentoomaniac** [comment]
Ah now I get it :)
just one improvement then: replace "if($outfile)" with "if($caching)" as $outfile will be always set in the linked code (if I read it correctly)

We could also move the if statement then in create_thumb and let it do the magic to read from the cache
(In that case maybe rename it to get_resized_image or something like that)

**Comment by Shulyaka** [comment]
Now I guess this one is also obsoleted by #13 .

**Comment by gentoomaniac** [comment]
jup. *trashit*

**Pull request closed without merging**
