### PR TITLE
createthumbnail improvements

### PR DESCRIPTION
**Pull request by Shulyaka**
Check this out, I think I've found the solution for createthumbnail to avoid any double work and code duplication

### CODE REVIEW

**Comment by Shulyaka** [comment]
Hi Marco,

Apparently we both modified the same things (the createthumb script). So, what are your plans for this pull requests (creating thumbnail and write cache in one path, auto detect thumb/small by size, other minor fixes)? Should I merge it with your latest commits or would you like to do it yourself?

**Comment by gentoomaniac** [comment]
Can you port  0335875 and  e29cdfc on the latest getimage.php?
Created a new pull request for the changes in 4c298fc which is imo a better solution. let me know if you see issues with that.

**Comment by Shulyaka** [comment]
Yes, sure, I will port that

**Comment by gentoomaniac** [comment]
@Shulyaka base it on the branch config_i18n which contains basic support for both. some stuff might be broken though, need to check.

**Comment by Shulyaka** [comment]
Done, please check.
Now this pull request is obsoleted by #13

**Pull request closed without merging**
