### PR TITLE
Fullscreen

### PR DESCRIPTION
**Pull request by Shulyaka**
Added a fullscreen button.

### CODE REVIEW

**Comment by gentoomaniac** [comment]
Awesome stuff!

However seems to not resize propperly when switching back to non-window mode (google-chrome)

**Comment by Shulyaka** [comment]
I've tested it in google chrome and it worked for me. Could you please
describe the steps to reproduce and provide a screen shot, if possible?
24 марта 2015 г. 2:05 пользователь "Marco Siebecke" <
notifications@github.com> написал:

**Comment by gentoomaniac** [comment]
Clicked on a picture, in the box on the fullscreen button, closed directly.
div#mbCenter seems to be resided incorrectly.

http://postimg.org/image/noii74hvj/
That is the content of the browser window. As you can see it resizes out of the window into nirvana :)

**Comment by gentoomaniac** [comment]
Think I got the "why".
I'm running the browser windows not maximized :)

Similar stuff happens btw with IE11, too. There the controls are at least still visible, but in fullscreen the picture is a bit moved to the left and not exactly centered.

**Pull request merged**
